name: abosiefienapp
description: A new Flutter project.
publish_to: 'none'

version: 1.2.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.12
  flutter_screenutil: ^5.9.0
  fluttertoast: ^9.0.0
  bot_toast: ^4.1.1
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.2.3
  date_picker_plus: ^6.0.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  flutter_barcode_scanner_plus: ^3.0.8
  realm: ^3.0.0
  path_provider: ^2.0.10
  dartz: ^0.10.1
  connectivity_plus: ^7.0.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  toastification: ^2.1.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.3
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
